### ISSUE TITLE
es6 Imports

### ISSUE THREAD

**Issue by gunins** [evilsoft/crocks#146]
Hi
Thanks, for very useful library. Any plans to replace `require` to es6 `import`? es6 `import` will be more natural, and since latest versions of chrome and nodejs is supporting them, will work on client and server.

**Comment by evilsoft** [comment]
There are indeed plans, but even though the latest v8 version supports it now, need to wait for (2) things: AWS Lambda to move to the latest version of node and the rest of the browsers to catch up. One of the things I do personally, is bring in ramda and crocks functions into a "helpers" file where I:
```js
export const State = require('crocks/State')
export const evolve = require('ramda/src/evolve')
...

// then I can
import { evolve, State } from '../utils/helpers'
```
There are other benefits to this approach (while we wait for the world to catch up). The problem is, it puts people who are not transpiling in the awkward position to have to `require('crocks/Sum').default` all over the place. Soon though, it will be a requirement to have this done before we go to 1.x.

That said, I am open to suggestions to avoid the `.default` thing and get this out sooner.

**Comment by evilsoft** [comment]
@gunins Okay. Was talking with someone today and I have a solution to make every one happy.
Will have es6 module support in the next release.

**Comment by gunins** [comment]
That's will be great. New chrome and Nodejs support es6 modules nativelly.

Thanks!

**Comment by bennypowers** [comment]
Please consider appending the `.js` extention to import paths, which would allow importing crocks members directly in the browser, sans build-step.

```html
<script type="module">
import Async from '/node_modules/crocks/src/Async/index.js';
</script>
```

date-fns follows this approach, see for example https://github.com/date-fns/date-fns/blob/master/src/esm/index.js

**Comment by dalefrancis88** [comment]
This seems to have a resolution, feel free to open if there is any more to add here
