### ISSUE TITLE
Add propOr on Maybe

### ISSUE THREAD

**Issue by HenriqueLimas** [evilsoft/crocks#157]
IMHO should be nice to have a `propOr` function to use in addition to `prop` on the `Maybe` module, where we can pass a default value when the prop is not there. Maybe composing 'default' and 'prop' together can be an idea. I can create a PR if you want.

**Comment by evilsoft** [comment]
`propOr` and `propPathOr` are not specifically in there because I assumed that people would want to keep things in the `Maybe` for further expansion. For example say I want a prop that needs to be a number, I can then do things like:
```js
const chain = require('crocks/pointfree/chain')
const compose = require('crocks/helpers/compose')
const isNumber = require('crocks/predicates/isNumber')
const prop = require('crocks/Maybe/prop')
const safe = require('crocks/Maybe/safe')

const validNumber = key =>
  compose(chain(safe(isNumber)), prop(key))
```

So it made sense that if a user would want to "stay" in the vanilla JS they would either bring it in from a lib like ramda or tiny-func or something that stays in JS. If you think there is value in adding this to `crocks` then, heck yeah, submit a PR.

But I do not think Maybe is the place for it as it does not return a Maybe all the time. It will have a signature like `propOr :: a -> String -> b -> c` 
```js
// propOr :: a -> String -> b -> c
function propOr(def, key, data) {
  ...
}
```

So I am think this should live inside of `helpers` as it really has nothing to do with `Maybe`. When implementing, try to use the bare minimum of `crocks` functions as this will bloat stack traces on errors, and only use function inside of the `core` folder. Will keep some :eyes: out for a PR.

And if you want, might as well make `propPathOr`.

**Comment by evilsoft** [comment]
PR is merged.
Looks like this feller should be closed.
