### ISSUE TITLE
Const and its Applicative constraints.

### ISSUE THREAD

**Issue by neonphlux** [evilsoft/crocks#278]
Hello.

Firstly, I would like to thank you for providing this library, it's lovely.

I'm learning Javascript so maybe you are already aware of this and haven't implemented it for reasons that are beyond my knowledge. 
I noticed that the Const doesn't behave as expected, since it doesn't 'enforce' the monoid contraint. For the Const to be able to be an Applicative, it has to provide a pure/return function:

```
class Functor f => Applicative f where
  pure :: a -> f a
  ...

``` 

`data a b = Const a`

Looking at "pure"'s signature, we observe that is impossible to provide a value for the monoid, since it only accepts one parameter. But by enforcing the first type variable of Const to be a monoid, we can conjure a value for Const out of nothing, by just providing a monoid type.

` repl> pure "hello" :: Const <which monoid?> String`

But with monoid:

```
repl> pure "hello" :: Const (Sum Int) String
repl> Const (Sum 0) // Sum Int! I know how to provide you with the empty value of that!

```
That also allows gives us other abilities like:

```
repl> liftA3(_ => _ => _ => undefined, Const(10), Const(30), Const(50))
repl> Const (90)
```

Again, thank you so much for the open-source.

**Comment by evilsoft** [comment]
So in the beginning I went back and forth on this. At the time we did not really have a notion of Type Constructors (this was before Writer, and please do not look at that one, there will be a bunch of breaking changes going out on that after the FL stuff is finished). So at the time I did not want to limit it to just work with the Monoid 🌽straint.

Also we did not have `First` implemented, so it made sense to make `Const` more like `Constant` and allow it to act as a poor-person's `First` and just lock down to a value. I figured that I would address this when the time came.

With this issue, it appears that the time has come. 😄.

So as the person making the request, how do you think we should implement, here are a couple options (and I am way open to more), because of the need for `of` and `empty` we will need to def go the type constructor route:

* Lock `Const` down to always use a `Monoid`  by taking a `Monoid` TypeRep. If a non-Monoid TypeRep is provided we throw a TypeError.

* Allow for all TypeReps (including constructors of JS types like `Array`, `Object`, `String`) and if `of`, `ap`, `empty` or `concat` is used we Throw a type error. (although we could probably allow `concat` for `Semigroups`, but that is debatable.

In both of the solutions we will be getting rid of `chain`, that part was from my lack of knowledge at the time.

**Comment by evilsoft** [comment]
Also, curious how you use it. I have only ever used for the traversable case, which seems like an extra step in JS. But some examples of how you, personally, would use it in JS could really help guide the implementation.

**Comment by evilsoft** [comment]
@neonphlux 
So in playing around last night I found a couple reasons to add this. As it sits right now, it is kinda pointless as we have `First`. It also will open the gate for adding the ability to provided `Array` and `String` constructors as type reps for Monoids.

So I think we should implement and gong to go with the second suggestion as we can do things like lens implementations and what have you. Thanks so much for taking the time to put in an issue for this!

**Comment by neonphlux** [comment]
That's so cool! Great job, Ian!
