### ISSUE TITLE
Curry on fn passed to lift functions

### ISSUE THREAD

**Issue by dalefrancis88** [evilsoft/crocks#335]
I wouldn't say it's a problem more a curiosity. Right now if we wanted to we could just `curry` a function as needed when passing it to a `lift` function `liftA2(curry(prod), Just(3), Just(3))` however it could be a nice added feature to not need to curry. 

**Code**
https://repl.it/@DaleFrancis/ensureCurry

**Comment by dalefrancis88** [comment]
@evilsoft @bennypowers @karthikiyengar Guys, Whats your thoughts on this one? do we think it's necessary or should we close it out?

**Comment by karthikiyengar** [comment]
@dalefrancis88 - Although it would be convenient and desirable in 99% of the cases, there could still be an edge case here:

```
liftA2((a, b) => (c) => a + c))
```
`b` is an optional parameter, and it should work perfectly fine - but it will cause problems if our autocurry kicks in. 

Also it would not really in parity with `ap` on the individual applicative functors. 

```
Just((a, b) => a + b).ap(Just(1)).ap(Just(2))
```

Since `liftA2` is just a pointfree version of the `ap`, we would also have to consider making the above work - which doesn't really feel intuitive to me. 


Btw, sorry for the MIA - been awfully busy lately

**Comment by dalefrancis88** [comment]
OffTopic: All good it happens, It'll be mine turn shortly for MIA, starting some hectic house renovations which i'm doing most of the heavy lifting

Yeah i can see that being a problem. Given that this is one of those things where it's pretty easy to solve it by just calling `curry` in your code-base and a potential world of hurt trying to add the fix in, I suggest lets wait till someone comments in Gitter with issues or someone requests the feature here. thoughts?

**Comment by karthikiyengar** [comment]
We can certainly wait, but even then I'm not really sure if it's a good idea because of JS's non-curried by default behavior. I can't think of any other userland (non-crocks) functions that we autocurry off the top of my head. But, of course I'll let the others weigh in here.

**Comment by dalefrancis88** [comment]
While there is so much to do i think it's best to work on completing that before we start to look into things like this. I think this will be a bigger discussion and thought experiment when we do decide to work on it. Will close this for now
