### ISSUE TITLE
Ability to choose which input param to pass to a func

### ISSUE THREAD

**Issue by dalefrancis88** [evilsoft/crocks#401]
**Is your feature request related to a problem? Please describe.**
Yes, their are some frameworks where the event handlers pass the instance of the component as the first param. 

**Describe the solution you'd like**
I'd like to see a function i could use to choose which param to take and pass to a containing func

**Describe alternatives for how you do this now**
I write in place funcs `(_, a) => f(a)`

**Code**
```
import { curry } from 'crocks'

const param = curry((index, f) => (...args) => f(args[index]))
const param1 = (index, f) => (...args) => f(args[index])

param(2, x => x + 2)(2, 3)
param1(2, x => x + 2)(2, 3, 4, 5, 6)
```

**Comment by dalefrancis88** [comment]
This is how Ramda implemented it

**Comment by RichardForrester** [comment]
I'd like to chime in here with my opinion on this subject.

First, Crocks is a fantastic library, and I think adoption is going to start growing fast. It's beautiful, practical, accessible, and very much idiomatic javascript. With the added educational tools showing up on Youtube and Egghead, I'm very excited to watch the success of this project as it unfolds; and, I'd very much like to be a part of it.

I've been surveying different functional libraries in javascript for the past few weeks, specifically Sanctuary, Folktale, Crocks and various smaller libs from folks like Dr. Boolean and others. I have lot of different comments on each of them. Also, like many others coming to the deeper levels functional programing through javascript, I also have years of experience with utility libraries like Lodash, Lodash/fp, and Ramda.

While all of the above packages are javascript, and are somewhat compatible with each other, i.e., it is possible to use some parts of this lib and parts of that lib, there is one underlying decision that each of those libraries made that fundamentally determines compatibility with existing code bases and existing third-party libraries. That decision is how to handle currying.

The following are my arguments for why Crocks should adopt a philosophy of 100% or as close to 100% compatibility and interoperability with Ramda and Ramda style currying.

1. Ramda famously does not provide ADTs.
1. Crocks's focus is on providing high quality ADTs.
1. Ramda is idiomatic javascript.
1. Crocks is idiomatic javascript, more in the vein of a Professor Frisby where in contrast Sanctuary has taken a hard-line approach to be as much like Haskell as possible and Folktale is coming from a Scala type mind-set.
1. The point of 1-4 above is that Crocks and Ramda already have similar philosophies but cover separate and complimentary needs. 
1. Sanctuary has abandoned its Ramda roots and has [adopted simple currying](https://github.com/sanctuary-js/sanctuary/issues/438) in order to facilitate a complex run-time type checking system.
1. Simple curry style is fundamentally incompatible with Ramda style curry.
1. It is inadvisable for any one code base to adopt multiple styles of currying due to compatibility issues. 
1. Almost all javascript programmers looking for ADTs will have experience using Ramda and probably have codebases that rely heavily upon Ramda style curry.
1. Ramda functions will defer to methods on ADTs if they exist; meaning, e.g., where refactoring a Ramda pointfree codebase, one would import Crock's constructor functions to replace some of Ramda's functions, such as `find` where the instantiation ADT is desired, there is no need to replace Ramda's `map` with Crock's `map`. 

Obviously, much of the above is just opinion, but I think there is an opportunity here for Crocks to fill a real need in the javascript community: idiomatic javascript ADTs that are fully compatible with javascript's most popular FP utility library.

**Comment by RichardForrester** [comment]
I had posted a big support for this but then removed it because I’ve been going back and forth. I can see a lot of pros and cons to the three different styles of currying, Ramda style, Simple Curry (Sanctuary), and the basic curry that Crocks currently uses. On balance, I think that the Ramda style is best for the consumer of the API. Of course the downside is that it increases the complexity of the library for the authors/contributors.

I think this is a good proposal and my only suggestion is that if Crocks does implement a placeholder it should be compatible with Ramda. I remember when I switched from lodash to Ramda it was a bit weird if you curried your own functions with one library and tried to use with the other.

**Comment by RichardForrester** [comment]
I keep seeing this issue thinking that you’re  talking about a placeholder. Can’t you just use nthArg from Ramda?

**Comment by dalefrancis88** [comment]
Quite possibly but while for some it's common to use Ramda many people don't use it in conjunction with crocks. It's a bad habit to just grab all the libraries for the sake of a few functions and so if it would be valuable within the library it gets put forward as a discussion point. 

Other than "it's already in Ramda" do you see a major issue with it?

**Comment by evilsoft** [comment]
TBH, It is my opinion that writing the in place function could read a bit better, because you can provide the name of the argument you are trying to capture and can see the "shape" of the function. That is the reason I am opposed to adding placeholders to crocks. Puts an undue cognitive burden, in my opinion, on anyone else (including future me) that has to parse and maintain it.

This could also open a can of "well what if I want the second and third".

I can say the same thing with this. BUT unlike placeholders, I am not totes opposed personally, if this gets support I do not see why this would be bad thing (other than possible additional cognitive load). Although we may wanna come up with a better name (says the person with no good examples of what that should be).

**Comment by RichardForrester** [comment]
No issue with nthArg specifically. I suppose it's a difficult philosophical problem for library authors to decide just exactly where to draw these lines regarding compatibility/duplication with/of other libraries.

I will say that If Crocks is meant to completely supplant a utility library like Ramda, then it has a lot of missing functionality. It may serve to make a list of all the functions Ramda provides, separating the functions that should return an ADT, e.g., `head`, from those that merely operate on and return native arrays and objects or a provided data structure.

Speaking personally, I came looking into Crocks, Folktale, Sanctuary and others because Ramda does not provide Maybe and Either - simple as that. All of the functions that should return a Maybe can return undefined which is just not acceptable. The vast majority of Ramda's functions however don't suffer from that problem and I see no reason to duplicate them. I think it's okay to assume people will be tree-shaking.

**Comment by dalefrancis88** [comment]
closing for now till we find enough requests to validate adding it to the library
